### ISSUE TITLE
babel 7 changed their entire namespace

### ISSUE THREAD

**Issue by createthis** [SimonDegraeve/hapi-webpack-plugin#21]
we can no longer do:

```js
require('babel-polyfill');
```

It's now:

```js
require('@babel/polyfill');
```

this package needs to be updated for babel 7 compatibility:

https://github.com/SimonDegraeve/hapi-webpack-plugin/blob/1d9544ea4336634a13426f49d2722fef3fb8c489/src/index.js#L4

**Comment by Kamahl19** [comment]
It seems this package is unmaintained so I decided to rewrite it in TS and fix all the issues. You can find it here https://github.com/Kamahl19/hapi-webpack-plugin-2

**Comment by RDP07** [comment]
Why does no one write tests on there code!!!!!

**Comment by RDP07** [comment]
@SimonDegraeve do you plan on maintaining/updating?

**Comment by SimonDegraeve** [comment]
unfortunately no, I am not planning to maintain this repo anymore. Sorry.
