### ISSUE TITLE
Hot options not working

### ISSUE THREAD

**Issue by Dindaleon** [SimonDegraeve/hapi-webpack-plugin#3]
Hello Simon, 

I am trying to activate the reload function for webpack-hot-middleware like this:

```
var hot = {
  // webpack-hot-middleware options 
  // See https://github.com/glenjamin/webpack-hot-middleware 
  reload:true
}
```

The asset's options do work though. And if I set reload to true in the webpack's entry settings works as well.

**Comment by SimonDegraeve** [comment]
Hi,

I am not sure to understand what are you expecting with `reload: true` option.
According to [webpack-hot-middleware code](https://github.com/glenjamin/webpack-hot-middleware/blob/master/middleware.js#L7-L10) the middleware only accept `log`, `path` or `heartbeat`.

The reload option is for the `client` not the `middleware` and can be passed to the client by adding querystring parameters to the path in the webpack config. See the [documentation](https://github.com/glenjamin/webpack-hot-middleware#config).
